#!/usr/bin/env python3
"""
Generates app/schema.sql and app/schema_manifest.json from schema/v1_items.csv.

schema/v1_items.csv is a checked-in extract of the "v1" tab of the source
Google Sheet (Area, Item, Description, Measurement/Type, Configured in
Settings as Manual Input?, Read from New Date Entry?). Every row becomes one
column on the `entries` table, so a single dated entry row is a full
snapshot of goals, targets and status metrics for that day.

Re-run this whenever the v1 tab changes:
    python3 schema/generate_schema.py
"""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "schema" / "v1_items.csv"
SQL_OUT = ROOT / "app" / "schema.sql"
MANIFEST_OUT = ROOT / "app" / "schema_manifest.json"

# Measurement/Type -> SQLite column type
TYPE_MAP = {
    "kg": "REAL",
    "%": "REAL",
    "kg/m^2": "REAL",
    "kcal": "REAL",
    "cal": "REAL",
    "g": "REAL",
    "days": "REAL",
    "hours": "REAL",
    "minutes": "REAL",
    "text": "TEXT",
}


def to_snake_case(item: str) -> str:
    s = item.lower()
    s = s.replace("1rm", "1rm ")
    s = re.sub(r"[^a-z0-9]+", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    # normalise inconsistent source naming
    s = s.replace("percentage_body_fat", "percent_body_fat")
    return s


def load_rows():
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return list(reader)


def build_manifest(rows):
    columns = []
    seen = set()
    for row in rows:
        column = to_snake_case(row["item"])
        if column in seen:
            raise ValueError(f"Duplicate generated column name: {column}")
        seen.add(column)
        sql_type = TYPE_MAP.get(row["measurement_type"].strip(), "REAL")
        columns.append(
            {
                "column": column,
                "area": row["area"],
                "item": row["item"],
                "description": row["description"],
                "measurement_type": row["measurement_type"],
                "sql_type": sql_type,
                "configured_in_settings": row["configured_in_settings"].strip().lower() == "true",
                "read_from_new_date_entry": row["read_from_new_date_entry"].strip().lower() == "true",
            }
        )
    return columns


def build_sql(columns):
    lines = [
        "-- Auto-generated by schema/generate_schema.py. Do not edit by hand.",
        "-- Regenerate with: python3 schema/generate_schema.py",
        "",
        "PRAGMA foreign_keys = ON;",
        "",
        "CREATE TABLE IF NOT EXISTS entries (",
        "    id TEXT PRIMARY KEY,            -- UUID4, generated on first insert",
        "    entry_date TEXT NOT NULL UNIQUE, -- ISO 8601 (YYYY-MM-DD), sourced from a dd/mm/yyyy sheet cell",
        "    source_row_number INTEGER,       -- row number in the Google Sheet, for traceability",
        "    created_at TEXT NOT NULL,        -- ISO 8601 UTC timestamp, first sync",
        "    updated_at TEXT NOT NULL,        -- ISO 8601 UTC timestamp, most recent sync",
    ]
    for i, col in enumerate(columns):
        trailing_comma = "," if i < len(columns) - 1 else ""
        lines.append(
            f"    {col['column']} {col['sql_type']}{trailing_comma}  "
            f"-- {col['area']}: {col['item']} ({col['measurement_type']})"
        )
    lines.append(");")
    lines.append("")
    lines.append("CREATE INDEX IF NOT EXISTS idx_entries_entry_date ON entries(entry_date);")
    lines.append("")
    lines.append("CREATE TABLE IF NOT EXISTS app_settings (")
    lines.append("    id INTEGER PRIMARY KEY CHECK (id = 1),  -- single row")
    lines.append("    google_sheet_id TEXT,")
    lines.append("    entries_tab_name TEXT NOT NULL DEFAULT 'v1',")
    lines.append("    date_column_name TEXT NOT NULL DEFAULT 'Date',")
    lines.append("    sync_interval_minutes INTEGER NOT NULL DEFAULT 10,")
    lines.append("    timezone TEXT NOT NULL DEFAULT 'America/Toronto',")
    lines.append("    service_account_json TEXT,  -- pasted service account credentials, JSON")
    lines.append("    last_sync_at TEXT,")
    lines.append("    last_sync_status TEXT,")
    lines.append("    last_sync_message TEXT,")
    lines.append("    updated_at TEXT")
    lines.append(");")
    lines.append("")
    lines.append(
        "INSERT OR IGNORE INTO app_settings (id, entries_tab_name, date_column_name, sync_interval_minutes, timezone) "
        "VALUES (1, 'v1', 'Date', 10, 'America/Toronto');"
    )
    lines.append("")
    return "\n".join(lines)


def main():
    rows = load_rows()
    columns = build_manifest(rows)
    MANIFEST_OUT.write_text(json.dumps({"source": "v1", "columns": columns}, indent=2) + "\n")
    SQL_OUT.write_text(build_sql(columns))
    print(f"Wrote {len(columns)} columns to {MANIFEST_OUT} and {SQL_OUT}")


if __name__ == "__main__":
    main()
